<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=0.9">
    <#include "../../webData/starter.ftlh">
    <link rel="stylesheet" href="../../../static/css/loginPage.css"/>
</head>

<div class="form-container">
    <h1>Coś poszło nie tak</h1>
    <p>${error}</p>
    <p>Proszę spróbować ponownie później lub skontaktować się z administratorem.</p>
    <p><a href="/">Wróć na stronę główną</a></p>
</div>


</html>